spring:
  datasource:
    # 도커 내부 접속: 서비스명(db) + 3306 포트
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST} # docker-compose의 서비스명
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}