spring:
  application:
    name: SpringStudy
  # spring 서버 local에서 IntelliJ로 띄울 때
  # application-dev.yaml 등 읽어오기 위해선 active 필요
  profiles:
    active: dev
    group:
      dev:
        - "dev"
        - "dev-db"
      prod:
        - "prod"
        - "prod-db"
      test:
        - "test"
        - "test-db"
    # config:
    # [중요] 로컬에 있는 .env 파일을 읽어 변수로 등록합니다.
    # import: optional:file:.env[.properties]

# context path
server:
  servlet:
    context-path: /api/v1

# --- 모니터링 설정 (Actuator) ---
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}