spring:
  application:
    name: SpringStudy
    # profiles:
    # active: dev
    group:
      dev:
        - "dev"
        - "dev-db"
      prod:
        - "prod"
        - "prod-db"
      test:
        - "test"
        - "test-db"
    # config:
    # [중요] 로컬에 있는 .env 파일을 읽어 변수로 등록합니다.
    # import: optional:file:.env[.properties]

# context path
server:
  servlet:
    context-path: /api/v1