spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}      # .env의 MYSQL_USER 값
    password: ${MYSQL_PASSWORD}  # .env의 MYSQL_PASSWORD 값
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD} # .env의 REDIS_PASSWORD 값